### ISSUE TITLE
界面

### ISSUE THREAD

**Issue by heocenxu** [niujt/Hospital#2]
你好giter，我想问下为什么启动了之后页面出现登录不了

**Comment by niujt** [comment]
检查一下数据库吧

**Comment by eddylin07** [comment]
没有webapp这个文件夹么。。

**Comment by eddylin07** [comment]
同样的问题，2020-10-08 14:28:16.285  WARN 10552 --- [nio-8088-exec-3] o.s.web.servlet.PageNotFound             : No mapping found for HTTP request with URI [/regist] in DispatcherServlet with name 'dispatcherServlet'

**Comment by 987863997** [comment]
同样的问题无法登陆

**Comment by niujt** [comment]
fixed

**Comment by liuhaojiqiren** [comment]
[ERROR] Some problems were encountered while processing the POMs:
[ERROR] Malformed POM D:\医疗系统\Hospital-master\pom.xml: expected START_TAG or END_TAG not TEXT (position: TEXT seen ...org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">\n    <m... @2:7)  @ D:\医疗系统\Hospital-master\pom.xml, line 2, column 7
 @ 
[ERROR] The build could not read 1 project -> [Help 1]
[ERROR]   
[ERROR]   The project org.springframework.boot:HospitalAction:1.0 (D:\医疗系统\Hospital-master\pom.xml) has 1 error
[ERROR]     Malformed POM D:\医疗系统\Hospital-master\pom.xml: expected START_TAG or END_TAG not TEXT (position: TEXT seen ...org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">\n    <m... @2:7)  @ D:\医疗系统\Hospital-master\pom.xml, line 2, column 7 -> [Help 2]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articl
这是啥情况
